/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LoRD Ju$uCH
 */

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Home extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        conn = javaConnect.ConnectDb();
        CurrentDate();
        updateTable();
    }
    
    public void updateTable(){
        //CUSTOM METHOD THAT SHOWS DATA ONTO THE DATA TABLE AND UPDATES ACCORDINGLY
        try{
            String sql = "SELECT EmployeeID, FirstName, Surname, Age, Title, Gender, Department, Shift, EmployeeGP FROM employees";
            
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            dataTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception ex){
                
            }
        }
    }
      
    public void CurrentDate(){
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    lblDate.setText("Date " + day + "- " + (month + 1) + "- " + year );
                    
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    lblTime.setText("Time " + hour + ":" + (min) + ":" + sec );
                    
                    try{
                        sleep(1000);
                    }
                    catch(InterruptedException ex){
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }                    
                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        radioButtonMale = new javax.swing.JRadioButton();
        txtShift = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtEmployeeGP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioButtonFemale = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonUpdate = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonGenerateReport = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        buttonLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        buttonShow = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        lblExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        lblFAQ = new javax.swing.JMenuItem();
        lblDate = new javax.swing.JMenu();
        lblTime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management System");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\JET FIRE VENTURES\\INTERNAL\\jetfire_logo_2-removebg-preview.png")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Medium", 1, 24), new java.awt.Color(59, 180, 48))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Gender");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Employee GP");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Surname");

        buttonGroup1.add(radioButtonMale);
        radioButtonMale.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        radioButtonMale.setText("Male");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Age");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Department");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Shift");

        buttonGroup1.add(radioButtonFemale);
        radioButtonFemale.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        radioButtonFemale.setText("Female");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Title");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(44, 44, 44)
                        .addComponent(radioButtonMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioButtonFemale)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtShift)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtSurname)
                            .addComponent(txtAge)
                            .addComponent(txtDepartment)
                            .addComponent(txtEmployeeGP)
                            .addComponent(txtTitle)
                            .addComponent(txtEmployeeID))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonMale)
                    .addComponent(radioButtonFemale)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeGP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Medium", 1, 18), new java.awt.Color(59, 180, 48))); // NOI18N

        buttonUpdate.setBackground(new java.awt.Color(0, 220, 0));
        buttonUpdate.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-update-20.png")); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(34, 217, 165));
        buttonSave.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonSave.setForeground(new java.awt.Color(255, 255, 255));
        buttonSave.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-save-20.png")); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonClear.setBackground(new java.awt.Color(0, 220, 0));
        buttonClear.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonClear.setForeground(new java.awt.Color(255, 255, 255));
        buttonClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-clear-20.png")); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(255, 9, 29));
        buttonDelete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-delete-20.png")); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonSave)
                .addGap(21, 21, 21)
                .addComponent(buttonUpdate)
                .addGap(21, 21, 21)
                .addComponent(buttonClear)
                .addGap(21, 21, 21)
                .addComponent(buttonDelete)
                .addGap(16, 16, 16))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonClear, buttonSave, buttonUpdate});

        buttonGenerateReport.setBackground(new java.awt.Color(243, 174, 61));
        buttonGenerateReport.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonGenerateReport.setForeground(new java.awt.Color(255, 255, 255));
        buttonGenerateReport.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-report-20.png")); // NOI18N
        buttonGenerateReport.setText("Generate Report");
        buttonGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateReportActionPerformed(evt);
            }
        });

        buttonPrint.setBackground(new java.awt.Color(188, 28, 240));
        buttonPrint.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        buttonPrint.setForeground(new java.awt.Color(255, 255, 255));
        buttonPrint.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-print-20.png")); // NOI18N
        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            dataTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(dataTable);

    buttonLogout.setBackground(new java.awt.Color(73, 120, 147));
    buttonLogout.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    buttonLogout.setForeground(new java.awt.Color(255, 255, 255));
    buttonLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-log-out-30.png")); // NOI18N
    buttonLogout.setText("Log out");
    buttonLogout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonLogoutActionPerformed(evt);
        }
    });

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 18), new java.awt.Color(59, 180, 48))); // NOI18N

    jLabel9.setFont(new java.awt.Font("sansserif", 2, 10)); // NOI18N
    jLabel9.setText("Search, ID, Name, Surname");

    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtSearchKeyReleased(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel9)
                    .addGap(0, 41, Short.MAX_VALUE))
                .addComponent(txtSearch))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(1, 1, 1)
            .addComponent(jLabel9)
            .addContainerGap())
    );

    buttonShow.setBackground(new java.awt.Color(73, 120, 147));
    buttonShow.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    buttonShow.setForeground(new java.awt.Color(255, 255, 255));
    buttonShow.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-show-28.png")); // NOI18N
    buttonShow.setText("Show");
    buttonShow.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonShowActionPerformed(evt);
        }
    });

    txtTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

    jLabel10.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
    jLabel10.setText("Total Employees");

    jMenu1.setText("File");

    lblExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\MR.KENNETH MUSUYA\\Desktop\\EMS App Dependecies\\icons8-exit-20.png")); // NOI18N
    lblExit.setText("Exit");
    lblExit.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lblExitActionPerformed(evt);
        }
    });
    jMenu1.add(lblExit);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Help");

    lblFAQ.setText("FAQs");
    jMenu3.add(lblFAQ);

    jMenuBar1.add(jMenu3);

    lblDate.setText("Date");
    jMenuBar1.add(lblDate);

    lblTime.setText("Time");
    jMenuBar1.add(lblTime);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonLogout)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(8, 8, 8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(64, Short.MAX_VALUE))
    );

    setSize(new java.awt.Dimension(1012, 849));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        // TODO add your handling code here:
        try{
            dispose();
            new LogInForm().setVisible(true);            
        }
        finally{
            try{
                rs.close();
                pst.close();   
            }
            catch(Exception ex){
            
            }
        }
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void lblExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO employees(EmployeeID, FirstName, Surname, Age, Title, Gender, Department, Shift, EmployeeGP)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst =  conn.prepareStatement(sql);
            pst.setString(1, txtEmployeeID.getText());
            pst.setString(2, txtFirstName.getText());
            pst.setString(3, txtSurname.getText());
            pst.setString(4, txtAge.getText());
            pst.setString(5, txtTitle.getText());
            
            radioButtonMale.setActionCommand("Male");
            radioButtonFemale.setActionCommand("Female");
            
            pst.setString(6, buttonGroup1.getSelection().getActionCommand());
            
            pst.setString(7, txtDepartment.getText());
            pst.setString(8, txtShift.getText());
            pst.setString(9, txtEmployeeGP.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Saved");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }updateTable();
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // This Button code stub Deletes data once selected and updates record in both database and data table
        
        int p = JOptionPane.showConfirmDialog(null, "Are You Sure","Delete",JOptionPane.YES_NO_OPTION);
        
        if (p == 0 ) {
            String sql = "DELETE FROM employees WHERE EmployeeID = ?";
            
            try{
                pst = conn.prepareCall(sql);
                pst.setString(1,txtEmployeeID.getText());
                pst.execute();
                
                JOptionPane.showMessageDialog(null, "Deleted");
                
            }catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        updateTable();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // This click event populates data to the text boxes to from the data table
        
        
        int row = dataTable.getSelectedRow();
        String tableClicked = (dataTable.getModel().getValueAt(row, 0).toString());
        try{
            String sql = "SELECT * FROM employees WHERE EmployeeID = '"+tableClicked+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()){
                
                String add1 = rs.getString("EmployeeID");
                txtEmployeeID.setText(add1);
                
                String add2 = rs.getString("FirstName");
                txtFirstName.setText(add2);
                
                String add3 = rs.getString("Surname");
                txtSurname.setText(add3);

                String add4 = rs.getString("Age");
                txtAge.setText(add4);

                String add5 = rs.getString("Title");
                txtTitle.setText(add5);
                
                radioButtonMale.setActionCommand("Male");
                radioButtonFemale.setActionCommand("Female");
                
                String add6 = rs.getString("Gender");
                
                if (add6.equals("Male")) {
                    radioButtonMale.setSelected(true);
                } else if (add6.equals("Female")) {
                    radioButtonFemale.setSelected(true);
            }
            
                String add7 = rs.getString("Department");
                txtDepartment.setText(add7);
                
                String add8 = rs.getString("Shift");
                txtShift.setText(add8);
                
                String add9 = rs.getString("EmployeeGP");
                txtEmployeeGP.setText(add9);
                
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_dataTableMouseClicked

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        // Code stub clears data on the text fields when selected.
        txtEmployeeID.setText("");
        txtFirstName.setText("");
        txtSurname.setText("");
        txtAge.setText("");
        txtTitle.setText("");

        buttonGroup1.clearSelection();
        
        txtDepartment.setText("");
        txtShift.setText("");
        txtEmployeeGP.setText("");
        txtFirstName.setText("");
    }//GEN-LAST:event_buttonClearActionPerformed

    private void buttonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowActionPerformed
        // Shows sum of all employees on to the textbox
        try{
            String sql = "SELECT COUNT(EmployeeID) FROM employees";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.next()){
                String sum = rs.getString("COUNT(EmployeeID)");
                txtTotal.setText(sum);
                
                txtTotal.setBackground(Color.GREEN);
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_buttonShowActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // CODE STUB UPDATES THE RECORDS WHEN DISPLAYED ONTO THE TEXT FIELDS
        try{
            int selectedRowIndex = dataTable.getSelectedRow();
            if (selectedRowIndex == -1){
                JOptionPane.showMessageDialog(null, "Please Select a record");
                return;
            }
            
            String employeeID =  dataTable.getModel().getValueAt(selectedRowIndex, 0).toString();
            
            String sql = "UPDATE employees SET FirstName = ?,Surname = ?, Age = ?, Title = ?, Gender = ?, Department = ?, Shift = ?, EmployeeGP = ? WHERE EmployeeID = ?";  
            pst = conn.prepareStatement(sql);
            
            pst.setString(1,txtFirstName.getText());
            pst.setString(2,txtSurname.getText());
            pst.setString(3,txtAge.getText());
            pst.setString(4,txtTitle.getText());
            
            pst.setString(5,buttonGroup1.getSelection().getActionCommand());
            
            pst.setString(6,txtDepartment.getText());
            pst.setString(7,txtShift.getText());
            pst.setString(8,txtEmployeeGP.getText());
            pst.setString(9,employeeID);
           
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Updated");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }updateTable();
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        // CODE STUB PERFORMS PRINT OPERATION AND GENERATES PDF FILE OF DATA ON THE TABLE
        
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("Page(0, number, integer");
        
        try{
            /*PrintRequestAttributeSet attr = new HashPrintRequestAttributeSet();
            attr.add(OrientationRequested.LANDSCAPE);*/ // Set landscape orientation
            
            dataTable.print(javax.swing.JTable.PrintMode.NORMAL, header, footer);
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n ", e.getMessage());
        }
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // CODE STUB PERFORMS SEARCH BY NAME
        
        try{
            
            String sql = "SELECT * FROM employees WHERE FirstName = ? ";
            pst =  conn.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());
            rs = pst.executeQuery();
            
            if (rs.next()){
                
                String add1 = rs.getString("EmployeeID");
                txtEmployeeID.setText(add1);
                
                String add2 = rs.getString("FirstName");
                txtFirstName.setText(add2);
                
                String add3 = rs.getString("Surname");
                txtSurname.setText(add3);

                String add4 = rs.getString("Age");
                txtAge.setText(add4);

                String add5 = rs.getString("Title");
                txtTitle.setText(add5);
                
                radioButtonMale.setActionCommand("Male");
                radioButtonFemale.setActionCommand("Female");
                
                String add6 = rs.getString("Gender");
                
                if (add6.equals("Male")) {
                    radioButtonMale.setSelected(true);
                } else if (add6.equals("Female")) {
                    radioButtonFemale.setSelected(true);
            }
            
                String add7 = rs.getString("Department");
                txtDepartment.setText(add7);
                
                String add8 = rs.getString("Shift");
                txtShift.setText(add8);
                
                String add9 = rs.getString("EmployeeGP");
                txtEmployeeGP.setText(add9);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void buttonGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateReportActionPerformed
        // Code below generates a pdf report of the employees information, gives manager's comment and training required for the employee
        
        String value1 = txtEmployeeID.getText();
        String value2 = txtFirstName.getText();
        String value3 = txtSurname.getText();
        String value4 = txtAge.getText();
        String value5 = txtTitle.getText();
        String value6 = buttonGroup1.getSelection().getActionCommand();
        String value7 = txtDepartment.getText();
        String value8 = txtShift.getText();
        String value9 = txtEmployeeGP.getText();
        
        try{
            Document document =  new Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));
            document.open();
            
            Image image = Image.getInstance("jetfire_logo.png");
            document.add(new Paragraph(""));
            document.add(image);
            
            document.add(new Paragraph("                                   JETFIRE VENTURES", FontFactory.getFont(FontFactory.TIMES_BOLD, 18, Font.BOLD, BaseColor.GREEN)));
            document.add(new Paragraph("           "           
                    +""));
            //document.add(new Paragraph(new Date().toString()));
            PdfPTable table = new PdfPTable(4);
            
            PdfPCell cell = new PdfPCell(new Paragraph("Employee info"));
            cell.setColspan(8);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.GREEN);
            cell.setPadding(10.0f);
            table.addCell(cell);
            
            table.addCell("EmployeeID");
            table.addCell(value1);
            table.addCell("FirstName");
            table.addCell(value2);
            table.addCell("Surname");
            table.addCell(value3);
            table.addCell("Age");
            table.addCell(value4);
            table.addCell("Title");
            table.addCell(value5);
            table.addCell("Gender");
            table.addCell(value6);
            table.addCell("Department");
            table.addCell(value7);
            table.addCell("Shift");
            table.addCell(value8);
            table.addCell("EmployeeGP");
            table.addCell(value9);
            
            document.add(table);
            
            com.itextpdf.text.List list = new com.itextpdf.text.List(true,20);
            document.add(new Paragraph("Assesment",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.RED)));
            
            list.add("First    =     68 %");
            list.add("Second   =     51 %");
            list.add("Thrid    =     85 %");
            list.add("Fourth   =     33 %");
            
            document.add(list);
            document.add(new Paragraph("Qualification Required",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.RED)));
            
            PdfPTable table1 = new PdfPTable(3);
            
            PdfPCell cell1 = new PdfPCell(new Paragraph("Training Required"));
            cell1.setColspan(8);
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setBackgroundColor(BaseColor.YELLOW);
            cell1.setPadding(5.0f);
            
            table.addCell(cell1);
            
            table1.addCell("Java");
            table1.addCell("SQL Database");
            table1.addCell("C#");
            table1.addCell("JavaScript");
            table1.addCell("Python");
            document.add(table1);
            
            document.add(new Paragraph("Manager's Comments", FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD, BaseColor.RED)));
            document.add(new Paragraph("\n(Proactive Maintenance Management Assistance)"));
            
            document.close();
            JOptionPane.showMessageDialog(null, "Report Saved Successfully");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_buttonGenerateReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonGenerateReport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton buttonShow;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu lblDate;
    private javax.swing.JMenuItem lblExit;
    private javax.swing.JMenuItem lblFAQ;
    private javax.swing.JMenu lblTime;
    private javax.swing.JRadioButton radioButtonFemale;
    private javax.swing.JRadioButton radioButtonMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmployeeGP;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtShift;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename = null;
    int s = 0;
    byte[] person_image = null;
    private String gender;
}
